image: Ubuntu

skip_tags: true
branches:
  only:
    - nonexisted

environment:
  GITHUB_USER:
    secure: qozx3wkmakdI3k/sz9Ml8Q==
  GITHUB_EMAIL:
    secure: Xou4FEHMweGQSeay5Q9/LjoLWwlDzMmBa39KYVylgK0=
  GITHUB_TOKEN:
    secure: HImK7idCBTKUB6w7DRTDV/5Ko9+TlZCLOXjbuGNb+InxYQm+H72G8fNPKVcrfcEz
  ACCOUNTS:
    secure: 2VuqzpIC2mUrw/rSYqvDWtm0pygI8os0EJZ5Jal2R7dN1BUuEQ+y3jTKDaLsnCc1BwSGL/H47/7/Q1hfOBodcxqaKPZfeAUtKbgqgd5DOghxAteYpeJYYq4g6j5JOYAw

build_script:
  - echo "ACCOUNTS=$ACCOUNTS" > .env
  - touch accounts.txt
  - docker run -v /dev/shm:/dev/shm -v $APPVEYOR_BUILD_FOLDER/accounts.txt:/working/accounts.txt --env-file .env wangkexiong/qiandao python3 appveyor.py
  - ./appveyor_update_github.sh
