language: python
python:
- 3.7

env:
  global:
  - REPO=wangkexiong/qiandao
  - secure: bUb3lQnEw5XERH24ZBk8jJQwoztYhWb/+XU95tP9JpaWPP7KrTKb5G7frjQanigKlGnv3OnnYxm7sxv8/Kxte422E1HeqtBq0W62dPDLp2aoSayJlccNwhGzLvno+MeTQ5ADnWShwqgQyi/hO51zXyRrZu90hpeozR1QoIJ5gbXBbe0undLp3DO+t+4GKfyFxItaMG4RF79U1sNnQCvQl5sh6wOvlTzXk/4Kco1CwGkKbT/ShVCuI0mBMGaJ8tK/QSUjloAIVxK7GyPprcmVQK9gWqZY8yXbr65vxjPE9N8xAX0uTg2lg83fMEidC6BxJDJqUal7kAckwYJ6hN93yxDmVOm6RJuAwX/l+PyEfNUz1pc2NJ7Id7PrizmjfJxTPTyhkIBqmn8Nuu7uCcdalsFAfpcHD75Ghl7Ivue3jb0/vtKAff97mjvc14K4cGrad63+H9sJ94zS1C317JbmXE7eF/MpSMnNOwekdT1JrOx9twBNU5Ln6MExExaoroeQHF+Gl6rdDBkW2zqhBI9X4BFxs6bZwm0lbvZwpDa2tLRGFCQK9nW3xLxehUddtWe3nOlDzGY3vCKVVOl5Tct8fLv7iTdK0kU53iX2iRvg9IJFtD06ZTn2n4yfE3DjwvRsmYaQXxBIJeVbJmF8mQfHiLcoSo+zPZ1Cd+rpWeHYEhs=
  - secure: pznZNhN02/lBunxVGDyl1ECn7l5hdzRIevmnIXT+c9mYd/+aEQqAObjYLF7N1agIAt6ze9l4wHkW0OqE1WH1AnjABVE8dxiFO7tk2g8Xyo2XFfAPtjlbpAALrkU3B69bgXJD0Ce/5LVqS7nt97kKWYHIKB5hsyKn5Iv7Lg+KJZf6hnUt6U0/LtQ5FVkUWv5083xeSfpFvENy4Lji75qjG81HFHfpvtPV3zc7LU5e1b0XziPx0ESEugUfAAYrP+4RUUFAK5eMB0y9gFbCYGyWD+qEE/o9k384aNMjYn4jYzjOvpgiExapo0g2WcImvqitTTVrftnkmuNdIzQYoP0JqixvngYAgp23VEYIIqgG2cJjoRC4J1KgkmJUdOdamm1kMERVmQxKeyrmw50jjFeiHV9SUHJ3gVerw1Nu4J2Ha6aU4qlUFvlYiU/LWYG4jUqXZkJzsOfh/X2vJAO4bOxORQ7MMiD+O4B49PJlkLmgat7OmNGk18Jgso9Fd7905AApx+OudG4yl27a8748XxOhThRYUuZMr6KqzsAh+7pNbaDRvdfUBY3J0aNQNygaeqoC2Yz4cOAzf9nDugdHmYOwuzjQ9/EtyNElHBX3h9Y6ZnJBpCBVaZUphdS/P0ybwldhJNe2lXe9Usgfb2JY5AlNOhI8S6wlkod8RfAtxa06P4Q=

services:
- docker

install:
- docker build -t $REPO .

script:
- docker run $REPO python3 --version

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker push $REPO
